//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Home : Navbar, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture11;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture10;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture8;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture7;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture4;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture1;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture6;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_SettingsIcon;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture5;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture13;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture14;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture15;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture2;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture4;
        
        private bool m_Initialized_Home;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf1;
        
        public Home() {
            this.InitializeComponent();
            this.m_MultiPicture4.MouseDown += new System.EventHandler(this.m_MultiPicture4_Action_MouseDown);
            this.m_Picture6.MouseDown += new System.EventHandler(this.m_Picture6_Action_MouseDown);
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.m_Button1.Click += new System.EventHandler(this.m_Button1_Action_Click);
            this.m_Picture2.MouseDown += new System.EventHandler(this.m_Picture2_Action_MouseDown);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture11 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture11);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture10 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture10);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter SettingsIcon {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_SettingsIcon);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture13 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture13);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture14 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture14);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture15 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture15);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture4);
            }
        }
        
        private void InitializeComponent() {
            this.brushdynamicsconvertercf1 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem1 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem2 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem3 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem4 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem5 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem6 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval1 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval2 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Picture11 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Picture10 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Picture8 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Picture7 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_MultiPicture4 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_MultiPicture1 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_MultiPicture = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Picture6 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_SettingsIcon = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Picture5 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Picture13 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Picture14 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Picture15 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Picture2 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Picture4 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture11)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_SettingsIcon)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture13)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture14)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture15)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture4)).BeginInit();
            this.SuspendLayout();
            // 
            // Home
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(214)))), ((int)(((byte)(227)))), ((int)(((byte)(244))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Picture11
            // 
            this.m_Picture11.BlinkDynamicsValue = false;
            this.m_Picture11.DelayMouseInputPeriod = 0;
            this.m_Picture11.EnabledDynamicsValue = true;
            this.m_Picture11.Height = 89;
            this.m_Picture11.IsBlinkEnabled = true;
            this.m_Picture11.Left = 663;
            this.m_Picture11.Name = "m_Picture11";
            this.m_Picture11.ScreenOwnerName = "Home";
            this.m_Picture11.Stretch = true;
            this.m_Picture11.SymbolName = "warning";
            this.m_Picture11.Top = 153;
            this.m_Picture11.VisibleDynamicsValue = true;
            this.m_Picture11.Width = 88;
            // 
            // m_Picture10
            // 
            this.m_Picture10.BlinkDynamicsValue = false;
            this.m_Picture10.DelayMouseInputPeriod = 0;
            this.m_Picture10.EnabledDynamicsValue = true;
            this.m_Picture10.Height = 89;
            this.m_Picture10.IsBlinkEnabled = true;
            this.m_Picture10.Left = 39;
            this.m_Picture10.Name = "m_Picture10";
            this.m_Picture10.ScreenOwnerName = "Home";
            this.m_Picture10.Stretch = true;
            this.m_Picture10.SymbolName = "warning";
            this.m_Picture10.Top = 153;
            this.m_Picture10.VisibleDynamicsValue = true;
            this.m_Picture10.Width = 88;
            // 
            // m_Picture8
            // 
            this.m_Picture8.BlinkDynamicsValue = false;
            this.m_Picture8.DelayMouseInputPeriod = 0;
            this.m_Picture8.EnabledDynamicsValue = true;
            this.m_Picture8.Height = 70;
            this.m_Picture8.IsBlinkEnabled = true;
            this.m_Picture8.Left = 665;
            this.m_Picture8.Name = "m_Picture8";
            this.m_Picture8.ScreenOwnerName = "Home";
            this.m_Picture8.Stretch = true;
            this.m_Picture8.SymbolName = "edited2";
            this.m_Picture8.Top = 163;
            this.m_Picture8.VisibleDynamicsValue = true;
            this.m_Picture8.Width = 71;
            // 
            // m_Picture7
            // 
            this.m_Picture7.BlinkDynamicsValue = false;
            this.m_Picture7.DelayMouseInputPeriod = 0;
            this.m_Picture7.EnabledDynamicsValue = true;
            this.m_Picture7.Height = 70;
            this.m_Picture7.IsBlinkEnabled = true;
            this.m_Picture7.Left = 56;
            this.m_Picture7.Name = "m_Picture7";
            this.m_Picture7.ScreenOwnerName = "Home";
            this.m_Picture7.Stretch = true;
            this.m_Picture7.SymbolName = "edited2";
            this.m_Picture7.Top = 162;
            this.m_Picture7.VisibleDynamicsValue = true;
            this.m_Picture7.Width = 71;
            // 
            // m_MultiPicture4
            // 
            this.m_MultiPicture4.BlinkDynamicsValue = false;
            this.m_MultiPicture4.DelayMouseInputPeriod = 0;
            this.m_MultiPicture4.EnabledDynamicsValue = true;
            this.m_MultiPicture4.Height = 60;
            this.m_MultiPicture4.Left = 735;
            this.m_MultiPicture4.Name = "m_MultiPicture4";
            this.m_MultiPicture4.ScreenOwnerName = "Home";
            this.m_MultiPicture4.Stretch = true;
            multisymbolitem1.SymbolName = "people";
            multisymbolitem1.Transparent = false;
            symbolinterval1.Value = multisymbolitem1;
            symbolinterval2.End = 1D;
            symbolinterval2.Start = 1D;
            multisymbolitem2.SymbolName = "people_highlighted";
            multisymbolitem2.Transparent = false;
            symbolinterval2.Value = multisymbolitem2;
            symbolintervalmapper1.Intervals.Add(symbolinterval1);
            symbolintervalmapper1.Intervals.Add(symbolinterval2);
            this.m_MultiPicture4.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_MultiPicture4.SymbolName = "people";
            this.m_MultiPicture4.Top = 3;
            this.m_MultiPicture4.Value = 0D;
            this.m_MultiPicture4.VisibleDynamicsValue = true;
            this.m_MultiPicture4.Width = 60;
            // 
            // m_MultiPicture1
            // 
            this.m_MultiPicture1.BlinkDynamicsValue = false;
            this.m_MultiPicture1.DelayMouseInputPeriod = 0;
            this.m_MultiPicture1.EnabledDynamicsValue = true;
            this.m_MultiPicture1.Height = 50;
            this.m_MultiPicture1.Left = 745;
            this.m_MultiPicture1.Name = "m_MultiPicture1";
            this.m_MultiPicture1.ScreenOwnerName = "Home";
            this.m_MultiPicture1.Stretch = true;
            multisymbolitem3.SymbolName = "wifi_disconnected";
            multisymbolitem3.Transparent = false;
            symbolinterval3.Value = multisymbolitem3;
            symbolinterval4.End = 1D;
            symbolinterval4.Start = 1D;
            multisymbolitem4.SymbolName = "wifi_connected";
            multisymbolitem4.Transparent = false;
            symbolinterval4.Value = multisymbolitem4;
            symbolintervalmapper2.Intervals.Add(symbolinterval3);
            symbolintervalmapper2.Intervals.Add(symbolinterval4);
            this.m_MultiPicture1.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_MultiPicture1.SymbolName = "wifi_disconnected";
            this.m_MultiPicture1.Top = 67;
            this.m_MultiPicture1.Value = 0D;
            this.m_MultiPicture1.VisibleDynamicsValue = true;
            this.m_MultiPicture1.Width = 50;
            // 
            // m_MultiPicture
            // 
            this.m_MultiPicture.BlinkDynamicsValue = false;
            this.m_MultiPicture.DelayMouseInputPeriod = 0;
            this.m_MultiPicture.EnabledDynamicsValue = true;
            this.m_MultiPicture.Height = 50;
            this.m_MultiPicture.Left = 745;
            this.m_MultiPicture.Name = "m_MultiPicture";
            this.m_MultiPicture.ScreenOwnerName = "Home";
            this.m_MultiPicture.Stretch = true;
            multisymbolitem5.SymbolName = "systemmanager_disconnected (2)";
            multisymbolitem5.Transparent = false;
            symbolinterval5.Value = multisymbolitem5;
            symbolinterval6.End = 1D;
            symbolinterval6.Start = 1D;
            multisymbolitem6.SymbolName = "systemmanager_connected (2)";
            multisymbolitem6.Transparent = false;
            symbolinterval6.Value = multisymbolitem6;
            symbolintervalmapper3.Intervals.Add(symbolinterval5);
            symbolintervalmapper3.Intervals.Add(symbolinterval6);
            this.m_MultiPicture.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_MultiPicture.SymbolName = "systemmanager_disconnected (2)";
            this.m_MultiPicture.Top = 127;
            this.m_MultiPicture.Value = 0D;
            this.m_MultiPicture.VisibleDynamicsValue = true;
            this.m_MultiPicture.Width = 50;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.DelayMouseInputPeriod = 0;
            this.m_Rectangle.EnabledDynamicsValue = true;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(214)))), ((int)(((byte)(227)))), ((int)(((byte)(244))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Height = 60;
            this.m_Rectangle.Left = 616;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "Home";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle.Top = -2;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 182;
            // 
            // m_Picture6
            // 
            this.m_Picture6.BlinkDynamicsValue = false;
            this.m_Picture6.DelayMouseInputPeriod = 0;
            this.m_Picture6.EnabledDynamicsValue = true;
            this.m_Picture6.Height = 62;
            this.m_Picture6.Left = 736;
            this.m_Picture6.Name = "m_Picture6";
            this.m_Picture6.ScreenOwnerName = "Home";
            this.m_Picture6.Stretch = true;
            this.m_Picture6.SymbolName = "people_logout";
            this.m_Picture6.Top = 0;
            this.m_Picture6.VisibleDynamicsValue = true;
            this.m_Picture6.Width = 62;
            // 
            // m_SettingsIcon
            // 
            this.m_SettingsIcon.BlinkDynamicsValue = false;
            this.m_SettingsIcon.DelayMouseInputPeriod = 0;
            this.m_SettingsIcon.EnabledDynamicsValue = true;
            this.m_SettingsIcon.Height = 50;
            this.m_SettingsIcon.Left = 616;
            this.m_SettingsIcon.Name = "m_SettingsIcon";
            this.m_SettingsIcon.ScreenOwnerName = "Home";
            this.m_SettingsIcon.Stretch = true;
            this.m_SettingsIcon.SymbolName = "settings";
            this.m_SettingsIcon.Top = 8;
            this.m_SettingsIcon.VisibleDynamicsValue = true;
            this.m_SettingsIcon.Width = 50;
            // 
            // m_Picture5
            // 
            this.m_Picture5.BlinkDynamicsValue = false;
            this.m_Picture5.DelayMouseInputPeriod = 0;
            this.m_Picture5.EnabledDynamicsValue = true;
            this.m_Picture5.Height = 240;
            this.m_Picture5.Left = 218;
            this.m_Picture5.Name = "m_Picture5";
            this.m_Picture5.ScreenOwnerName = "Home";
            this.m_Picture5.Stretch = true;
            this.m_Picture5.SymbolName = "optx2-agv (1)";
            this.m_Picture5.Top = 78;
            this.m_Picture5.VisibleDynamicsValue = true;
            this.m_Picture5.Width = 352;
            // 
            // m_Picture13
            // 
            this.m_Picture13.BlinkDynamicsValue = false;
            this.m_Picture13.DelayMouseInputPeriod = 0;
            this.m_Picture13.EnabledDynamicsValue = true;
            this.m_Picture13.Height = 40;
            this.m_Picture13.Left = 258;
            this.m_Picture13.Name = "m_Picture13";
            this.m_Picture13.ScreenOwnerName = "Home";
            this.m_Picture13.Stretch = true;
            this.m_Picture13.SymbolName = "estop";
            this.m_Picture13.Top = 102;
            this.m_Picture13.VisibleDynamicsValue = true;
            this.m_Picture13.Width = 40;
            // 
            // m_Picture14
            // 
            this.m_Picture14.BlinkDynamicsValue = false;
            this.m_Picture14.DelayMouseInputPeriod = 0;
            this.m_Picture14.EnabledDynamicsValue = true;
            this.m_Picture14.Height = 40;
            this.m_Picture14.Left = 258;
            this.m_Picture14.Name = "m_Picture14";
            this.m_Picture14.ScreenOwnerName = "Home";
            this.m_Picture14.Stretch = true;
            this.m_Picture14.SymbolName = "estop";
            this.m_Picture14.Top = 272;
            this.m_Picture14.VisibleDynamicsValue = true;
            this.m_Picture14.Width = 40;
            // 
            // m_Picture15
            // 
            this.m_Picture15.BlinkDynamicsValue = false;
            this.m_Picture15.DelayMouseInputPeriod = 0;
            this.m_Picture15.EnabledDynamicsValue = true;
            this.m_Picture15.Height = 40;
            this.m_Picture15.Left = 484;
            this.m_Picture15.Name = "m_Picture15";
            this.m_Picture15.ScreenOwnerName = "Home";
            this.m_Picture15.Stretch = true;
            this.m_Picture15.SymbolName = "estop";
            this.m_Picture15.Top = 272;
            this.m_Picture15.VisibleDynamicsValue = true;
            this.m_Picture15.Width = 40;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(188)))), ((int)(((byte)(166))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.Bold = true;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button.DelayMouseInputPeriod = 0;
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontSizePixels = 20;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            this.m_Button.Height = 50;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 680;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "Home";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Button.TextHeight = 24;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 108;
            this.m_Button.Top = 272;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -1548231914;
            this.m_Button.Width = 118;
            this.m_Button.WordWrap = true;
            // 
            // m_Button1
            // 
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.Bold = true;
            this.m_Button1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            brushdynamicsconvertercf1.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(188)))), ((int)(((byte)(166))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval1.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(188)))), ((int)(((byte)(166))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval2.End = 1D;
            brushcfinterval2.Start = 1D;
            brushcfinterval2.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(125)))), ((int)(((byte)(111))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval1);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval2);
            this.m_Button1.DelayMouseInputPeriod = 0;
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontSizePixels = 20;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            this.m_Button1.Height = 50;
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 665;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "Home";
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_Button1.TextHeight = 24;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 123;
            this.m_Button1.Top = 328;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = 304018137;
            this.m_Button1.Width = 133;
            this.m_Button1.WordWrap = true;
            // 
            // m_Picture2
            // 
            this.m_Picture2.BlinkDynamicsValue = false;
            this.m_Picture2.DelayMouseInputPeriod = 0;
            this.m_Picture2.EnabledDynamicsValue = true;
            this.m_Picture2.Height = 72;
            this.m_Picture2.Left = 664;
            this.m_Picture2.Name = "m_Picture2";
            this.m_Picture2.ScreenOwnerName = "Home";
            this.m_Picture2.Stretch = true;
            this.m_Picture2.SymbolName = "backward";
            this.m_Picture2.Top = -3;
            this.m_Picture2.VisibleDynamicsValue = true;
            this.m_Picture2.Width = 73;
            // 
            // m_Picture4
            // 
            this.m_Picture4.BlinkDynamicsValue = false;
            this.m_Picture4.DelayMouseInputPeriod = 0;
            this.m_Picture4.EnabledDynamicsValue = true;
            this.m_Picture4.Height = 40;
            this.m_Picture4.Left = 484;
            this.m_Picture4.Name = "m_Picture4";
            this.m_Picture4.ScreenOwnerName = "Home";
            this.m_Picture4.Stretch = true;
            this.m_Picture4.SymbolName = "estop";
            this.m_Picture4.Top = 102;
            this.m_Picture4.VisibleDynamicsValue = true;
            this.m_Picture4.Width = 40;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "Home";
            this.PopupScreen = false;
            this.ScreenID = ((ushort)(1));
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_Home = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
            this.SecurityExtender.SetSecurityGroupsRequired(this.m_Rectangle, SecurityGroups.Group_01 | SecurityGroups.Group_03);
            this.SecurityExtender.SetVisibilityOnAccessDenied(this.m_Rectangle, VisibilityModes.Hidden);
            this.SecurityExtender.SetSecurityGroupsRequired(this.m_Picture6, SecurityGroups.Group_01 | SecurityGroups.Group_03);
            this.SecurityExtender.SetVisibilityOnAccessDenied(this.m_Picture6, VisibilityModes.Hidden);
            this.SecurityExtender.SetSecurityGroupsRequired(this.m_SettingsIcon, SecurityGroups.Group_01);
            this.SecurityExtender.SetVisibilityOnAccessDenied(this.m_SettingsIcon, VisibilityModes.Hidden);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_Home) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Picture11);
            this.DrawingPrimitives.Add(this.m_Picture10);
            this.DrawingPrimitives.Add(this.m_Picture8);
            this.DrawingPrimitives.Add(this.m_Picture7);
            this.DrawingPrimitives.Add(this.m_MultiPicture4);
            this.DrawingPrimitives.Add(this.m_MultiPicture1);
            this.DrawingPrimitives.Add(this.m_MultiPicture);
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_Picture6);
            this.DrawingPrimitives.Add(this.m_SettingsIcon);
            this.DrawingPrimitives.Add(this.m_Picture5);
            this.DrawingPrimitives.Add(this.m_Picture13);
            this.DrawingPrimitives.Add(this.m_Picture14);
            this.DrawingPrimitives.Add(this.m_Picture15);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_Picture2);
            this.DrawingPrimitives.Add(this.m_Picture4);
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture11)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_SettingsIcon)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture13)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture14)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture15)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture4)).EndInit();
        }
        
        private void m_MultiPicture4_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_MultiPicture4", "MouseDown", "Login", "Security", "");
            Neo.ApplicationFramework.Generated.Globals.Security.Login();
        }
        
        private void m_Picture6_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Picture6", "MouseDown", "Logout", "Security", "");
            Neo.ApplicationFramework.Generated.Globals.Security.Logout();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Show Screen", "HomeScreenInfo", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.HomeScreenInfo.Show();
        }
        
        private void m_Button1_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "Click", "Set Tag", "Tags.BB_Trigger", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.BB_Trigger.SetTag();
        }
        
        private void m_Picture2_Action_MouseDown(object sender, System.EventArgs e) {
            Core.Api.Service.ServiceContainerCF.GetService<Neo.ApplicationFramework.Interfaces.IScreenManager>().LogActionBackScreen("m_Picture2", "MouseDown", "Show Previous Screen", "");
            Core.Api.Service.ServiceContainerCF.GetService<Neo.ApplicationFramework.Interfaces.IScreenManager>().ActionBackScreen();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Home));
            this.m_Button.Text = resources.GetText("Home.Button.Text", "HELP");
            this.m_Button1.Text = resources.GetText("Home.Button1.Text", "BLACKBOX");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_Home) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.RearScannerWarningField"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Picture11.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.FrontScannerWarningField"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Picture10.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.RearScannerStopField"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Picture8.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.FrontScannerStopField"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Picture7.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HighlightLogin"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture4.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.WIFI_Connection"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture1.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.SysMan_Connection"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding8 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.EStopActive"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Picture13.DataBindings.Add(dynamicBinding8);
            this.m_DynamicBindings.Add(dynamicBinding8);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding9 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.EStopActive"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Picture14.DataBindings.Add(dynamicBinding9);
            this.m_DynamicBindings.Add(dynamicBinding9);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding10 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.EStopActive"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Picture15.DataBindings.Add(dynamicBinding10);
            this.m_DynamicBindings.Add(dynamicBinding10);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding11 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.BB_Trigger"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf1);
            this.m_Button1.DataBindings.Add(dynamicBinding11);
            this.m_DynamicBindings.Add(dynamicBinding11);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding12 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.EStopActive"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Picture4.DataBindings.Add(dynamicBinding12);
            this.m_DynamicBindings.Add(dynamicBinding12);
        }
    }
}
