//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class HomeScreenInfo : Window640x480, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text13;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture12;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture3;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text3;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture4;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text4;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture5;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text5;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture6;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text6;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_AlarmInfo;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text8;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text10;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture13;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text12;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text14;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture1;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture7;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture8;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text19;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Group;
        
        private bool m_Initialized_HomeScreenInfo;
        
        public HomeScreenInfo() {
            this.InitializeComponent();
            this.Adapter.Closed += new System.EventHandler(this.HomeScreenInfo_Closed);
            this.Adapter.Opened += new System.EventHandler(this.HomeScreenInfo_Opened);
            this.m_Picture13.MouseDown += new System.EventHandler(this.m_Picture13_Action_MouseDown);
            this.m_Group.MouseDown += new System.EventHandler(this.m_Group_Action_PreviewMouseDown);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text13 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text13);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture12 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture12);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter AlarmInfo {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_AlarmInfo);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text10 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text10);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture13 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture13);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text12 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text12);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text14 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text14);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Group {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Group);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text19 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text19);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf1 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf1 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf2 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf2 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf3 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf4 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem1 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem2 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem3 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem4 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            this.m_Text13 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Picture12 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Picture = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Picture1 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Picture2 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Picture3 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Text3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Picture4 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Text4 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Picture5 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Text5 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Picture6 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Text6 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AlarmInfo = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text8 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text10 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Picture13 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Text12 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text14 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_MultiPicture1 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_MultiPicture = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_Picture7 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Picture8 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Text19 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Group = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text13)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture12)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AlarmInfo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture13)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text12)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text14)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text19)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group)).BeginInit();
            this.SuspendLayout();
            // 
            // HomeScreenInfo
            // 
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Text13
            // 
            this.m_Text13.BlinkDynamicsValue = false;
            this.m_Text13.DelayMouseInputPeriod = 0;
            this.m_Text13.EnabledDynamicsValue = true;
            this.m_Text13.FontSizePixels = 15;
            this.m_Text13.Height = 36;
            this.m_Text13.Left = 491;
            this.m_Text13.Name = "m_Text13";
            this.m_Text13.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3.75D, 0D, 3.75D, 1D);
            this.m_Text13.ScreenOwnerName = "HomeScreenInfo";
            this.m_Text13.Top = 303;
            this.m_Text13.VisibleDynamicsValue = true;
            this.m_Text13.Width = 113;
            // 
            // m_Picture12
            // 
            this.m_Picture12.BlinkDynamicsValue = false;
            this.m_Picture12.DelayMouseInputPeriod = 0;
            this.m_Picture12.EnabledDynamicsValue = true;
            this.m_Picture12.Height = 60;
            this.m_Picture12.Left = 415;
            this.m_Picture12.Name = "m_Picture12";
            this.m_Picture12.ScreenOwnerName = "HomeScreenInfo";
            this.m_Picture12.Stretch = true;
            this.m_Picture12.SymbolName = "people";
            this.m_Picture12.Top = 288;
            this.m_Picture12.VisibleDynamicsValue = true;
            this.m_Picture12.Width = 60;
            // 
            // m_Picture
            // 
            this.m_Picture.BlinkDynamicsValue = false;
            this.m_Picture.DelayMouseInputPeriod = 0;
            this.m_Picture.EnabledDynamicsValue = true;
            this.m_Picture.Height = 42;
            this.m_Picture.Left = 91;
            this.m_Picture.Name = "m_Picture";
            this.m_Picture.ScreenOwnerName = "HomeScreenInfo";
            this.m_Picture.Stretch = true;
            this.m_Picture.SymbolName = "moreicon";
            this.m_Picture.Top = 7;
            this.m_Picture.VisibleDynamicsValue = true;
            this.m_Picture.Width = 43;
            // 
            // m_Text
            // 
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.Bold = true;
            this.m_Text.DelayMouseInputPeriod = 0;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontSizePixels = 19;
            this.m_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            this.m_Text.Height = 36;
            this.m_Text.Left = 132;
            this.m_Text.Name = "m_Text";
            this.m_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4.75D, 0D, 4.75D, 1D);
            this.m_Text.ScreenOwnerName = "HomeScreenInfo";
            this.m_Text.Top = 7;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 193;
            // 
            // m_Picture1
            // 
            this.m_Picture1.BlinkDynamicsValue = false;
            this.m_Picture1.DelayMouseInputPeriod = 0;
            this.m_Picture1.EnabledDynamicsValue = true;
            this.m_Picture1.Height = 50;
            this.m_Picture1.Left = 102;
            this.m_Picture1.Name = "m_Picture1";
            this.m_Picture1.ScreenOwnerName = "HomeScreenInfo";
            this.m_Picture1.Stretch = true;
            this.m_Picture1.SymbolName = "canserversafestate (1)";
            this.m_Picture1.Top = 295;
            this.m_Picture1.VisibleDynamicsValue = true;
            this.m_Picture1.Width = 50;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.DelayMouseInputPeriod = 0;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontSizePixels = 20;
            this.m_Text1.Height = 36;
            this.m_Text1.Left = 167;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text1.ScreenOwnerName = "HomeScreenInfo";
            this.m_Text1.Top = 305;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 231;
            // 
            // m_Picture2
            // 
            this.m_Picture2.BlinkDynamicsValue = false;
            this.m_Picture2.DelayMouseInputPeriod = 0;
            this.m_Picture2.EnabledDynamicsValue = true;
            this.m_Picture2.Height = 50;
            this.m_Picture2.Left = 102;
            this.m_Picture2.Name = "m_Picture2";
            this.m_Picture2.ScreenOwnerName = "HomeScreenInfo";
            this.m_Picture2.Stretch = true;
            this.m_Picture2.SymbolName = "notinsystem_gapac";
            this.m_Picture2.Top = 360;
            this.m_Picture2.VisibleDynamicsValue = true;
            this.m_Picture2.Width = 50;
            // 
            // m_Text2
            // 
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.DelayMouseInputPeriod = 0;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontSizePixels = 20;
            this.m_Text2.Height = 36;
            this.m_Text2.Left = 167;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text2.ScreenOwnerName = "HomeScreenInfo";
            this.m_Text2.Top = 370;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 243;
            // 
            // m_Picture3
            // 
            this.m_Picture3.BlinkDynamicsValue = false;
            this.m_Picture3.DelayMouseInputPeriod = 0;
            this.m_Picture3.EnabledDynamicsValue = true;
            this.m_Picture3.Height = 50;
            this.m_Picture3.Left = 102;
            this.m_Picture3.Name = "m_Picture3";
            this.m_Picture3.ScreenOwnerName = "HomeScreenInfo";
            this.m_Picture3.Stretch = true;
            this.m_Picture3.SymbolName = "unknowspos (1)";
            this.m_Picture3.Top = 424;
            this.m_Picture3.VisibleDynamicsValue = true;
            this.m_Picture3.Width = 50;
            // 
            // m_Text3
            // 
            this.m_Text3.BlinkDynamicsValue = false;
            this.m_Text3.DelayMouseInputPeriod = 0;
            this.m_Text3.EnabledDynamicsValue = true;
            this.m_Text3.FontSizePixels = 20;
            this.m_Text3.Height = 36;
            this.m_Text3.Left = 167;
            this.m_Text3.Name = "m_Text3";
            this.m_Text3.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text3.ScreenOwnerName = "HomeScreenInfo";
            this.m_Text3.Top = 435;
            this.m_Text3.VisibleDynamicsValue = true;
            this.m_Text3.Width = 187;
            // 
            // m_Picture4
            // 
            this.m_Picture4.BlinkDynamicsValue = false;
            this.m_Picture4.DelayMouseInputPeriod = 0;
            this.m_Picture4.EnabledDynamicsValue = true;
            this.m_Picture4.Height = 50;
            this.m_Picture4.Left = 426;
            this.m_Picture4.Name = "m_Picture4";
            this.m_Picture4.ScreenOwnerName = "HomeScreenInfo";
            this.m_Picture4.Stretch = true;
            this.m_Picture4.SymbolName = "groundfault (1)";
            this.m_Picture4.Top = 77;
            this.m_Picture4.VisibleDynamicsValue = true;
            this.m_Picture4.Width = 50;
            // 
            // m_Text4
            // 
            this.m_Text4.BlinkDynamicsValue = false;
            this.m_Text4.DelayMouseInputPeriod = 0;
            this.m_Text4.EnabledDynamicsValue = true;
            this.m_Text4.FontSizePixels = 20;
            this.m_Text4.Height = 36;
            this.m_Text4.Left = 492;
            this.m_Text4.Name = "m_Text4";
            this.m_Text4.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text4.ScreenOwnerName = "HomeScreenInfo";
            this.m_Text4.Top = 87;
            this.m_Text4.VisibleDynamicsValue = true;
            this.m_Text4.Width = 199;
            // 
            // m_Picture5
            // 
            this.m_Picture5.BlinkDynamicsValue = false;
            this.m_Picture5.DelayMouseInputPeriod = 0;
            this.m_Picture5.EnabledDynamicsValue = true;
            this.m_Picture5.Height = 50;
            this.m_Picture5.Left = 102;
            this.m_Picture5.Name = "m_Picture5";
            this.m_Picture5.ScreenOwnerName = "HomeScreenInfo";
            this.m_Picture5.Stretch = true;
            this.m_Picture5.SymbolName = "allokey";
            this.m_Picture5.Top = 77;
            this.m_Picture5.VisibleDynamicsValue = true;
            this.m_Picture5.Width = 50;
            // 
            // m_Text5
            // 
            this.m_Text5.BlinkDynamicsValue = false;
            this.m_Text5.DelayMouseInputPeriod = 0;
            this.m_Text5.EnabledDynamicsValue = true;
            this.m_Text5.FontSizePixels = 20;
            this.m_Text5.Height = 36;
            this.m_Text5.Left = 167;
            this.m_Text5.Name = "m_Text5";
            this.m_Text5.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text5.ScreenOwnerName = "HomeScreenInfo";
            this.m_Text5.Top = 87;
            this.m_Text5.VisibleDynamicsValue = true;
            this.m_Text5.Width = 64;
            // 
            // m_Picture6
            // 
            this.m_Picture6.BlinkDynamicsValue = false;
            this.m_Picture6.DelayMouseInputPeriod = 0;
            this.m_Picture6.EnabledDynamicsValue = true;
            this.m_Picture6.Height = 50;
            this.m_Picture6.Left = 102;
            this.m_Picture6.Name = "m_Picture6";
            this.m_Picture6.ScreenOwnerName = "HomeScreenInfo";
            this.m_Picture6.Stretch = true;
            this.m_Picture6.SymbolName = "estop";
            this.m_Picture6.Top = 220;
            this.m_Picture6.VisibleDynamicsValue = true;
            this.m_Picture6.Width = 50;
            // 
            // m_Text6
            // 
            this.m_Text6.BlinkDynamicsValue = false;
            this.m_Text6.DelayMouseInputPeriod = 0;
            this.m_Text6.EnabledDynamicsValue = true;
            this.m_Text6.FontSizePixels = 20;
            this.m_Text6.Height = 36;
            this.m_Text6.Left = 167;
            this.m_Text6.Name = "m_Text6";
            this.m_Text6.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text6.ScreenOwnerName = "HomeScreenInfo";
            this.m_Text6.Top = 230;
            this.m_Text6.VisibleDynamicsValue = true;
            this.m_Text6.Width = 234;
            // 
            // m_AlarmInfo
            // 
            this.m_AlarmInfo.AutoSize = false;
            this.m_AlarmInfo.BlinkDynamicsValue = false;
            this.m_AlarmInfo.DelayMouseInputPeriod = 0;
            this.m_AlarmInfo.EnabledDynamicsValue = true;
            this.m_AlarmInfo.FontSizePixels = 20;
            this.m_AlarmInfo.Height = 59;
            this.m_AlarmInfo.Left = 167;
            this.m_AlarmInfo.Name = "m_AlarmInfo";
            this.m_AlarmInfo.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_AlarmInfo.ScreenOwnerName = "HomeScreenInfo";
            this.m_AlarmInfo.Top = 144;
            this.m_AlarmInfo.VisibleDynamicsValue = true;
            this.m_AlarmInfo.Width = 226;
            this.m_AlarmInfo.WordWrap = true;
            // 
            // m_Text8
            // 
            this.m_Text8.AutoSize = false;
            this.m_Text8.BlinkDynamicsValue = false;
            this.m_Text8.DelayMouseInputPeriod = 0;
            this.m_Text8.EnabledDynamicsValue = true;
            this.m_Text8.FontSizePixels = 20;
            this.m_Text8.Height = 50;
            this.m_Text8.Left = 492;
            this.m_Text8.Name = "m_Text8";
            this.m_Text8.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text8.ScreenOwnerName = "HomeScreenInfo";
            stringintervalmappercf1.DefaultValue = "Vehicle is disconnected from WLAN";
            stringintervalcf1.Value = "Vehicle is disconnected from WLAN";
            stringintervalcf2.End = 1D;
            stringintervalcf2.Start = 1D;
            stringintervalcf2.Value = "Vehicle is connected to WLAN";
            stringintervalmappercf1.Intervals.Add(stringintervalcf1);
            stringintervalmappercf1.Intervals.Add(stringintervalcf2);
            this.m_Text8.TextIntervalMapper = stringintervalmappercf1;
            this.m_Text8.TextVerticalAlignment = "Center";
            this.m_Text8.Top = 144;
            this.m_Text8.VisibleDynamicsValue = true;
            this.m_Text8.Width = 225;
            this.m_Text8.WordWrap = true;
            // 
            // m_Text10
            // 
            this.m_Text10.AutoSize = false;
            this.m_Text10.BlinkDynamicsValue = false;
            this.m_Text10.DelayMouseInputPeriod = 0;
            this.m_Text10.EnabledDynamicsValue = true;
            this.m_Text10.FontSizePixels = 20;
            this.m_Text10.Height = 57;
            this.m_Text10.Left = 491;
            this.m_Text10.Name = "m_Text10";
            this.m_Text10.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text10.ScreenOwnerName = "HomeScreenInfo";
            stringintervalmappercf2.DefaultValue = "Vehicle is disconnected from System Manager";
            stringintervalcf3.Value = "Vehicle is disconnected from System Manager";
            stringintervalcf4.End = 1D;
            stringintervalcf4.Start = 1D;
            stringintervalcf4.Value = "Vehicle is connected to System Manager";
            stringintervalmappercf2.Intervals.Add(stringintervalcf3);
            stringintervalmappercf2.Intervals.Add(stringintervalcf4);
            this.m_Text10.TextIntervalMapper = stringintervalmappercf2;
            this.m_Text10.TextVerticalAlignment = "Center";
            this.m_Text10.Top = 216;
            this.m_Text10.VisibleDynamicsValue = true;
            this.m_Text10.Width = 221;
            this.m_Text10.WordWrap = true;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.DelayMouseInputPeriod = 0;
            this.m_Rectangle.EnabledDynamicsValue = true;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Height = 69;
            this.m_Rectangle.Left = 415;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "HomeScreenInfo";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle.Top = 281;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 302;
            // 
            // m_Picture13
            // 
            this.m_Picture13.BlinkDynamicsValue = false;
            this.m_Picture13.DelayMouseInputPeriod = 0;
            this.m_Picture13.EnabledDynamicsValue = true;
            this.m_Picture13.Height = 62;
            this.m_Picture13.Left = 421;
            this.m_Picture13.Name = "m_Picture13";
            this.m_Picture13.ScreenOwnerName = "HomeScreenInfo";
            this.m_Picture13.Stretch = true;
            this.m_Picture13.SymbolName = "people_logout";
            this.m_Picture13.Top = 287;
            this.m_Picture13.VisibleDynamicsValue = true;
            this.m_Picture13.Width = 62;
            // 
            // m_Text12
            // 
            this.m_Text12.BlinkDynamicsValue = false;
            this.m_Text12.DelayMouseInputPeriod = 0;
            this.m_Text12.EnabledDynamicsValue = true;
            this.m_Text12.FontSizePixels = 20;
            this.m_Text12.Height = 36;
            this.m_Text12.Left = 491;
            this.m_Text12.Name = "m_Text12";
            this.m_Text12.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text12.ScreenOwnerName = "HomeScreenInfo";
            this.m_Text12.Top = 301;
            this.m_Text12.VisibleDynamicsValue = true;
            this.m_Text12.Width = 78;
            // 
            // m_Text14
            // 
            this.m_Text14.BlinkDynamicsValue = false;
            this.m_Text14.DelayMouseInputPeriod = 0;
            this.m_Text14.EnabledDynamicsValue = true;
            this.m_Text14.FontSizePixels = 20;
            this.m_Text14.Height = 36;
            this.m_Text14.Left = 562;
            this.m_Text14.Name = "m_Text14";
            this.m_Text14.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text14.ScreenOwnerName = "HomeScreenInfo";
            this.m_Text14.Top = 301;
            this.m_Text14.VisibleDynamicsValue = true;
            this.m_Text14.Width = 143;
            // 
            // m_MultiPicture1
            // 
            this.m_MultiPicture1.BlinkDynamicsValue = false;
            this.m_MultiPicture1.DelayMouseInputPeriod = 0;
            this.m_MultiPicture1.EnabledDynamicsValue = true;
            this.m_MultiPicture1.Height = 50;
            this.m_MultiPicture1.Left = 426;
            this.m_MultiPicture1.Name = "m_MultiPicture1";
            this.m_MultiPicture1.ScreenOwnerName = "HomeScreenInfo";
            this.m_MultiPicture1.Stretch = true;
            multisymbolitem1.SymbolName = "wifi_disconnected";
            multisymbolitem1.Transparent = false;
            symbolinterval1.Value = multisymbolitem1;
            symbolinterval2.End = 1D;
            symbolinterval2.Start = 1D;
            multisymbolitem2.SymbolName = "wifi_connected";
            multisymbolitem2.Transparent = false;
            symbolinterval2.Value = multisymbolitem2;
            symbolintervalmapper1.Intervals.Add(symbolinterval1);
            symbolintervalmapper1.Intervals.Add(symbolinterval2);
            this.m_MultiPicture1.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_MultiPicture1.SymbolName = "wifi_disconnected";
            this.m_MultiPicture1.Top = 153;
            this.m_MultiPicture1.Value = 0D;
            this.m_MultiPicture1.VisibleDynamicsValue = true;
            this.m_MultiPicture1.Width = 50;
            // 
            // m_MultiPicture
            // 
            this.m_MultiPicture.BlinkDynamicsValue = false;
            this.m_MultiPicture.DelayMouseInputPeriod = 0;
            this.m_MultiPicture.EnabledDynamicsValue = true;
            this.m_MultiPicture.Height = 50;
            this.m_MultiPicture.Left = 426;
            this.m_MultiPicture.Name = "m_MultiPicture";
            this.m_MultiPicture.ScreenOwnerName = "HomeScreenInfo";
            this.m_MultiPicture.Stretch = true;
            multisymbolitem3.SymbolName = "systemmanager_disconnected (2)";
            multisymbolitem3.Transparent = false;
            symbolinterval3.Value = multisymbolitem3;
            symbolinterval4.End = 1D;
            symbolinterval4.Start = 1D;
            multisymbolitem4.SymbolName = "systemmanager_connected (2)";
            multisymbolitem4.Transparent = false;
            symbolinterval4.Value = multisymbolitem4;
            symbolintervalmapper2.Intervals.Add(symbolinterval3);
            symbolintervalmapper2.Intervals.Add(symbolinterval4);
            this.m_MultiPicture.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_MultiPicture.SymbolName = "systemmanager_disconnected (2)";
            this.m_MultiPicture.Top = 220;
            this.m_MultiPicture.Value = 0D;
            this.m_MultiPicture.VisibleDynamicsValue = true;
            this.m_MultiPicture.Width = 50;
            // 
            // m_Picture7
            // 
            this.m_Picture7.BlinkDynamicsValue = false;
            this.m_Picture7.DelayMouseInputPeriod = 0;
            this.m_Picture7.EnabledDynamicsValue = true;
            this.m_Picture7.Height = 60;
            this.m_Picture7.IsBlinkEnabled = true;
            this.m_Picture7.Left = 0;
            this.m_Picture7.Name = "m_Picture7";
            this.m_Picture7.ScreenOwnerName = "HomeScreenInfo";
            this.m_Picture7.Stretch = true;
            this.m_Picture7.SymbolName = "warningbackground (1)";
            this.m_Picture7.Top = 0;
            this.m_Picture7.VisibleDynamicsValue = true;
            this.m_Picture7.Width = 60;
            // 
            // m_Picture8
            // 
            this.m_Picture8.BlinkDynamicsValue = false;
            this.m_Picture8.DelayMouseInputPeriod = 0;
            this.m_Picture8.EnabledDynamicsValue = true;
            this.m_Picture8.Height = 50;
            this.m_Picture8.Left = 5;
            this.m_Picture8.Name = "m_Picture8";
            this.m_Picture8.ScreenOwnerName = "HomeScreenInfo";
            this.m_Picture8.Stretch = true;
            this.m_Picture8.SymbolName = "warning3";
            this.m_Picture8.Top = 5;
            this.m_Picture8.VisibleDynamicsValue = true;
            this.m_Picture8.Width = 50;
            // 
            // m_Text19
            // 
            this.m_Text19.AutoSize = false;
            this.m_Text19.BlinkDynamicsValue = false;
            this.m_Text19.Bold = true;
            this.m_Text19.DelayMouseInputPeriod = 0;
            this.m_Text19.EnabledDynamicsValue = true;
            this.m_Text19.FontSizePixels = 16;
            this.m_Text19.Height = 33;
            this.m_Text19.Left = 0;
            this.m_Text19.Name = "m_Text19";
            this.m_Text19.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4D, 0D, 4D, 1D);
            this.m_Text19.ScreenOwnerName = "HomeScreenInfo";
            this.m_Text19.TextHorizontalAlignment = "Center";
            this.m_Text19.Top = 20;
            this.m_Text19.VisibleDynamicsValue = true;
            this.m_Text19.Width = 60;
            // 
            // m_Group
            // 
            this.m_Group.BlinkDynamicsValue = false;
            this.m_Group.Components.Add(this.m_Picture7);
            this.m_Group.Components.Add(this.m_Picture8);
            this.m_Group.Components.Add(this.m_Text19);
            this.m_Group.DelayMouseInputPeriod = 0;
            this.m_Group.EnabledDynamicsValue = true;
            this.m_Group.Height = 60;
            this.m_Group.Left = 97;
            this.m_Group.Name = "m_Group";
            this.m_Group.ParentGroup = null;
            this.m_Group.ScreenOwnerName = "HomeScreenInfo";
            this.m_Group.Top = 141;
            this.m_Group.VisibleDynamicsValue = true;
            this.m_Group.Width = 60;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "HomeScreenInfo";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_HomeScreenInfo = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
            this.SecurityExtender.SetSecurityGroupsRequired(this.m_Rectangle, SecurityGroups.Group_01 | SecurityGroups.Group_03);
            this.SecurityExtender.SetVisibilityOnAccessDenied(this.m_Rectangle, VisibilityModes.Hidden);
            this.SecurityExtender.SetSecurityGroupsRequired(this.m_Picture13, SecurityGroups.Group_01 | SecurityGroups.Group_03);
            this.SecurityExtender.SetVisibilityOnAccessDenied(this.m_Picture13, VisibilityModes.Hidden);
            this.SecurityExtender.SetSecurityGroupsRequired(this.m_Text12, SecurityGroups.Group_01 | SecurityGroups.Group_03);
            this.SecurityExtender.SetVisibilityOnAccessDenied(this.m_Text12, VisibilityModes.Hidden);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_HomeScreenInfo) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Text13);
            this.DrawingPrimitives.Add(this.m_Picture12);
            this.DrawingPrimitives.Add(this.m_Picture);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Picture1);
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_Picture2);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_Picture3);
            this.DrawingPrimitives.Add(this.m_Text3);
            this.DrawingPrimitives.Add(this.m_Picture4);
            this.DrawingPrimitives.Add(this.m_Text4);
            this.DrawingPrimitives.Add(this.m_Picture5);
            this.DrawingPrimitives.Add(this.m_Text5);
            this.DrawingPrimitives.Add(this.m_Picture6);
            this.DrawingPrimitives.Add(this.m_Text6);
            this.DrawingPrimitives.Add(this.m_AlarmInfo);
            this.DrawingPrimitives.Add(this.m_Text8);
            this.DrawingPrimitives.Add(this.m_Text10);
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_Picture13);
            this.DrawingPrimitives.Add(this.m_Text12);
            this.DrawingPrimitives.Add(this.m_Text14);
            this.DrawingPrimitives.Add(this.m_MultiPicture1);
            this.DrawingPrimitives.Add(this.m_MultiPicture);
            this.DrawingPrimitives.Add(this.m_Picture7);
            this.DrawingPrimitives.Add(this.m_Picture8);
            this.DrawingPrimitives.Add(this.m_Text19);
            this.DrawingPrimitives.Add(this.m_Group);
            ((System.ComponentModel.ISupportInitialize)(this.m_Text13)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture12)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AlarmInfo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture13)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text12)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text14)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text19)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group)).EndInit();
        }
        
        private void m_Picture13_Action_MouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Picture13", "MouseDown", "Logout", "Security", "");
            Neo.ApplicationFramework.Generated.Globals.Security.Logout();
        }
        
        private void m_Group_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Group", "MouseDown", "Show Screen", "Alarms", "");
            Neo.ApplicationFramework.Generated.Globals.Alarms.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(HomeScreenInfo));
            this.m_Text.Text = resources.GetText("HomeScreenInfo.Text.Text", "SCREEN SYMBOLS");
            this.m_Text1.Text = resources.GetText("HomeScreenInfo.Text1.Text", "CAN Server Safe State");
            this.m_Text2.Text = resources.GetText("HomeScreenInfo.Text2.Text", "Vehicle is not in system");
            this.m_Text3.Text = resources.GetText("HomeScreenInfo.Text3.Text", "Unknown position");
            this.m_Text4.Text = resources.GetText("HomeScreenInfo.Text4.Text", "Ground fault active");
            this.m_Text5.Text = resources.GetText("HomeScreenInfo.Text5.Text", "All ok");
            this.m_Text6.Text = resources.GetText("HomeScreenInfo.Text6.Text", "Emergency stop active");
            this.m_AlarmInfo.Text = resources.GetText("HomeScreenInfo.AlarmInfo.Text", "99 alarms active. Press to show active alarms.");
            this.m_Text8.Text = resources.GetText("HomeScreenInfo.Text8.Text", "Vehicle is disconnected from WLAN");
            this.m_Text10.Text = resources.GetText("HomeScreenInfo.Text10.Text", "Vehicle is disconnected from System Manager");
            this.m_Text12.Text = resources.GetText("HomeScreenInfo.Text12.Text", "Logout");
            this.m_Text13.Text = resources.GetText("HomeScreenInfo.Text13.Text", "Login user");
            this.m_Text14.Text = resources.GetText("HomeScreenInfo.Text14.Text", "Administrator");
            this.m_Text19.Text = resources.GetText("HomeScreenInfo.Text19.Text", "99");
            resources.ApplyTexts(this.m_Text10, "Texts", "HomeScreenInfo.Text10.Texts[0]", "Vehicle is disconnected from System Manager", "HomeScreenInfo.Text10.Texts[1]", "Vehicle is connected to System Manager");
            resources.ApplyTexts(this.m_Text8, "Texts", "HomeScreenInfo.Text8.Texts[0]", "Vehicle is disconnected from WLAN", "HomeScreenInfo.Text8.Texts[1]", "Vehicle is connected to WLAN");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_HomeScreenInfo) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.WIFI_Connection"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text8.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.SysMan_Connection"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text10.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.SystemTagCurrentUser"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text14.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.WIFI_Connection"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture1.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.SysMan_Connection"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.AlarmsActive"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Text19.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
        }
    }
}
