//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Assisted_Insert : Background, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_MultiPicture;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private bool m_Initialized_Assisted_Insert;
        
        public Assisted_Insert() {
            this.InitializeComponent();
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter MultiPicture {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_MultiPicture);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem1 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem2 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem3 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem4 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem5 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem6 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem7 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval8 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem8 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval9 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem9 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval10 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem10 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval11 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem11 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval12 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem12 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval13 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem13 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval14 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem14 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval15 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem15 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval16 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem16 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval17 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem17 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval18 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem18 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval19 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem19 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval20 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem20 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval21 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem21 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval22 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem22 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval23 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem23 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval24 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem24 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval25 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem25 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval26 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem26 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval27 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem27 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval28 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem28 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval29 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem29 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval30 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem30 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval31 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem31 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval32 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem32 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval33 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem33 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval34 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem34 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval35 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem35 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval36 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem36 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval37 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem37 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval38 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem38 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval39 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem39 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval40 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem40 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval41 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem41 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval42 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem42 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval43 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem43 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval44 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem44 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval45 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem45 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval46 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem46 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval47 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem47 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval48 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem48 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval49 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem49 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval50 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem50 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval51 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem51 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval52 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem52 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval53 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem53 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval54 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem54 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval55 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem55 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval56 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem56 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval57 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem57 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval58 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem58 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval59 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem59 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval60 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem60 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval61 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem61 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval62 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem62 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval63 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem63 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval64 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem64 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval65 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem65 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval66 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem66 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval67 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem67 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval68 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem68 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval69 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem69 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval70 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem70 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval71 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem71 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval72 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem72 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval73 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem73 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AnalogNumeric = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_MultiPicture = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            this.SuspendLayout();
            // 
            // Assisted_Insert
            // 
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Text
            // 
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.Bold = true;
            this.m_Text.DelayMouseInputPeriod = 0;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontSizePixels = 28;
            this.m_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            this.m_Text.Height = 25;
            this.m_Text.Left = 75;
            this.m_Text.Name = "m_Text";
            this.m_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(7D, 0D, 7D, 1D);
            this.m_Text.ScreenOwnerName = "Assisted_Insert";
            this.m_Text.Top = 6;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 122;
            // 
            // m_Text2
            // 
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.DelayMouseInputPeriod = 0;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontSizePixels = 20;
            this.m_Text2.Height = 25;
            this.m_Text2.Left = 128;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text2.ScreenOwnerName = "Assisted_Insert";
            this.m_Text2.Top = 152;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 151;
            // 
            // m_AnalogNumeric
            // 
            this.m_AnalogNumeric.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric.BlinkDynamicsValue = false;
            this.m_AnalogNumeric.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric.EnabledDynamicsValue = true;
            this.m_AnalogNumeric.FontSizePixels = 20;
            this.m_AnalogNumeric.Height = 30;
            this.m_AnalogNumeric.Left = 176;
            this.m_AnalogNumeric.Name = "m_AnalogNumeric";
            this.m_AnalogNumeric.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric.ScreenOwnerName = "Assisted_Insert";
            this.m_AnalogNumeric.Top = 216;
            this.m_AnalogNumeric.VisibleDynamicsValue = true;
            this.m_AnalogNumeric.Width = 100;
            // 
            // m_MultiPicture
            // 
            this.m_MultiPicture.BlinkDynamicsValue = false;
            this.m_MultiPicture.DelayMouseInputPeriod = 0;
            this.m_MultiPicture.EnabledDynamicsValue = true;
            this.m_MultiPicture.Height = 100;
            this.m_MultiPicture.Left = 520;
            this.m_MultiPicture.Name = "m_MultiPicture";
            this.m_MultiPicture.ScreenOwnerName = "Assisted_Insert";
            this.m_MultiPicture.Stretch = true;
            symbolinterval1.End = 2D;
            multisymbolitem1.SymbolName = "waypoint_0";
            multisymbolitem1.Transparent = false;
            symbolinterval1.Value = multisymbolitem1;
            symbolinterval2.End = 7D;
            symbolinterval2.Start = 3D;
            multisymbolitem2.SymbolName = "waypoint_5";
            multisymbolitem2.Transparent = false;
            symbolinterval2.Value = multisymbolitem2;
            symbolinterval3.End = 12D;
            symbolinterval3.Start = 8D;
            multisymbolitem3.SymbolName = "waypoint_10";
            multisymbolitem3.Transparent = false;
            symbolinterval3.Value = multisymbolitem3;
            symbolinterval4.End = 17D;
            symbolinterval4.Start = 13D;
            multisymbolitem4.SymbolName = "waypoint_15";
            multisymbolitem4.Transparent = false;
            symbolinterval4.Value = multisymbolitem4;
            symbolinterval5.End = 22D;
            symbolinterval5.Start = 18D;
            multisymbolitem5.SymbolName = "waypoint_20";
            multisymbolitem5.Transparent = false;
            symbolinterval5.Value = multisymbolitem5;
            symbolinterval6.End = 27D;
            symbolinterval6.Start = 23D;
            multisymbolitem6.SymbolName = "waypoint_25";
            multisymbolitem6.Transparent = false;
            symbolinterval6.Value = multisymbolitem6;
            symbolinterval7.End = 32D;
            symbolinterval7.Start = 28D;
            multisymbolitem7.SymbolName = "waypoint_30";
            multisymbolitem7.Transparent = false;
            symbolinterval7.Value = multisymbolitem7;
            symbolinterval8.End = 37D;
            symbolinterval8.Start = 33D;
            multisymbolitem8.SymbolName = "waypoint_35";
            multisymbolitem8.Transparent = false;
            symbolinterval8.Value = multisymbolitem8;
            symbolinterval9.End = 42D;
            symbolinterval9.Start = 38D;
            multisymbolitem9.SymbolName = "waypoint_40";
            multisymbolitem9.Transparent = false;
            symbolinterval9.Value = multisymbolitem9;
            symbolinterval10.End = 47D;
            symbolinterval10.Start = 43D;
            multisymbolitem10.SymbolName = "waypoint_45";
            multisymbolitem10.Transparent = false;
            symbolinterval10.Value = multisymbolitem10;
            symbolinterval11.End = 52D;
            symbolinterval11.Start = 48D;
            multisymbolitem11.SymbolName = "waypoint_50";
            multisymbolitem11.Transparent = false;
            symbolinterval11.Value = multisymbolitem11;
            symbolinterval12.End = 57D;
            symbolinterval12.Start = 53D;
            multisymbolitem12.SymbolName = "waypoint_55";
            multisymbolitem12.Transparent = false;
            symbolinterval12.Value = multisymbolitem12;
            symbolinterval13.End = 62D;
            symbolinterval13.Start = 58D;
            multisymbolitem13.SymbolName = "waypoint_60";
            multisymbolitem13.Transparent = false;
            symbolinterval13.Value = multisymbolitem13;
            symbolinterval14.End = 67D;
            symbolinterval14.Start = 63D;
            multisymbolitem14.SymbolName = "waypoint_65";
            multisymbolitem14.Transparent = false;
            symbolinterval14.Value = multisymbolitem14;
            symbolinterval15.End = 72D;
            symbolinterval15.Start = 68D;
            multisymbolitem15.SymbolName = "waypoint_70";
            multisymbolitem15.Transparent = false;
            symbolinterval15.Value = multisymbolitem15;
            symbolinterval16.End = 77D;
            symbolinterval16.Start = 73D;
            multisymbolitem16.SymbolName = "waypoint_75";
            multisymbolitem16.Transparent = false;
            symbolinterval16.Value = multisymbolitem16;
            symbolinterval17.End = 82D;
            symbolinterval17.Start = 78D;
            multisymbolitem17.SymbolName = "waypoint_80";
            multisymbolitem17.Transparent = false;
            symbolinterval17.Value = multisymbolitem17;
            symbolinterval18.End = 87D;
            symbolinterval18.Start = 83D;
            multisymbolitem18.SymbolName = "waypoint_85";
            multisymbolitem18.Transparent = false;
            symbolinterval18.Value = multisymbolitem18;
            symbolinterval19.End = 92D;
            symbolinterval19.Start = 88D;
            multisymbolitem19.SymbolName = "waypoint_90";
            multisymbolitem19.Transparent = false;
            symbolinterval19.Value = multisymbolitem19;
            symbolinterval20.End = 97D;
            symbolinterval20.Start = 93D;
            multisymbolitem20.SymbolName = "waypoint_95";
            multisymbolitem20.Transparent = false;
            symbolinterval20.Value = multisymbolitem20;
            symbolinterval21.End = 102D;
            symbolinterval21.Start = 98D;
            multisymbolitem21.SymbolName = "waypoint_100";
            multisymbolitem21.Transparent = false;
            symbolinterval21.Value = multisymbolitem21;
            symbolinterval22.End = 107D;
            symbolinterval22.Start = 103D;
            multisymbolitem22.SymbolName = "waypoint_105";
            multisymbolitem22.Transparent = false;
            symbolinterval22.Value = multisymbolitem22;
            symbolinterval23.End = 112D;
            symbolinterval23.Start = 108D;
            multisymbolitem23.SymbolName = "waypoint_110";
            multisymbolitem23.Transparent = false;
            symbolinterval23.Value = multisymbolitem23;
            symbolinterval24.End = 117D;
            symbolinterval24.Start = 113D;
            multisymbolitem24.SymbolName = "waypoint_115";
            multisymbolitem24.Transparent = false;
            symbolinterval24.Value = multisymbolitem24;
            symbolinterval25.End = 122D;
            symbolinterval25.Start = 118D;
            multisymbolitem25.SymbolName = "waypoint_120";
            multisymbolitem25.Transparent = false;
            symbolinterval25.Value = multisymbolitem25;
            symbolinterval26.End = 127D;
            symbolinterval26.Start = 123D;
            multisymbolitem26.SymbolName = "waypoint_125";
            multisymbolitem26.Transparent = false;
            symbolinterval26.Value = multisymbolitem26;
            symbolinterval27.End = 132D;
            symbolinterval27.Start = 128D;
            multisymbolitem27.SymbolName = "waypoint_130";
            multisymbolitem27.Transparent = false;
            symbolinterval27.Value = multisymbolitem27;
            symbolinterval28.End = 137D;
            symbolinterval28.Start = 133D;
            multisymbolitem28.SymbolName = "waypoint_135";
            multisymbolitem28.Transparent = false;
            symbolinterval28.Value = multisymbolitem28;
            symbolinterval29.End = 142D;
            symbolinterval29.Start = 138D;
            multisymbolitem29.SymbolName = "waypoint_140";
            multisymbolitem29.Transparent = false;
            symbolinterval29.Value = multisymbolitem29;
            symbolinterval30.End = 147D;
            symbolinterval30.Start = 143D;
            multisymbolitem30.SymbolName = "waypoint_145";
            multisymbolitem30.Transparent = false;
            symbolinterval30.Value = multisymbolitem30;
            symbolinterval31.End = 152D;
            symbolinterval31.Start = 148D;
            multisymbolitem31.SymbolName = "waypoint_150";
            multisymbolitem31.Transparent = false;
            symbolinterval31.Value = multisymbolitem31;
            symbolinterval32.End = 157D;
            symbolinterval32.Start = 153D;
            multisymbolitem32.SymbolName = "waypoint_155";
            multisymbolitem32.Transparent = false;
            symbolinterval32.Value = multisymbolitem32;
            symbolinterval33.End = 162D;
            symbolinterval33.Start = 158D;
            multisymbolitem33.SymbolName = "waypoint_160";
            multisymbolitem33.Transparent = false;
            symbolinterval33.Value = multisymbolitem33;
            symbolinterval34.End = 167D;
            symbolinterval34.Start = 163D;
            multisymbolitem34.SymbolName = "waypoint_165";
            multisymbolitem34.Transparent = false;
            symbolinterval34.Value = multisymbolitem34;
            symbolinterval35.End = 172D;
            symbolinterval35.Start = 168D;
            multisymbolitem35.SymbolName = "waypoint_170";
            multisymbolitem35.Transparent = false;
            symbolinterval35.Value = multisymbolitem35;
            symbolinterval36.End = 177D;
            symbolinterval36.Start = 173D;
            multisymbolitem36.SymbolName = "waypoint_175";
            multisymbolitem36.Transparent = false;
            symbolinterval36.Value = multisymbolitem36;
            symbolinterval37.End = 182D;
            symbolinterval37.Start = 178D;
            multisymbolitem37.SymbolName = "waypoint_180";
            multisymbolitem37.Transparent = false;
            symbolinterval37.Value = multisymbolitem37;
            symbolinterval38.End = 187D;
            symbolinterval38.Start = 183D;
            multisymbolitem38.SymbolName = "waypoint_185";
            multisymbolitem38.Transparent = false;
            symbolinterval38.Value = multisymbolitem38;
            symbolinterval39.End = 192D;
            symbolinterval39.Start = 188D;
            multisymbolitem39.SymbolName = "waypoint_190";
            multisymbolitem39.Transparent = false;
            symbolinterval39.Value = multisymbolitem39;
            symbolinterval40.End = 197D;
            symbolinterval40.Start = 193D;
            multisymbolitem40.SymbolName = "waypoint_195";
            multisymbolitem40.Transparent = false;
            symbolinterval40.Value = multisymbolitem40;
            symbolinterval41.End = 202D;
            symbolinterval41.Start = 198D;
            multisymbolitem41.SymbolName = "waypoint_200";
            multisymbolitem41.Transparent = false;
            symbolinterval41.Value = multisymbolitem41;
            symbolinterval42.End = 207D;
            symbolinterval42.Start = 203D;
            multisymbolitem42.SymbolName = "waypoint_205";
            multisymbolitem42.Transparent = false;
            symbolinterval42.Value = multisymbolitem42;
            symbolinterval43.End = 212D;
            symbolinterval43.Start = 208D;
            multisymbolitem43.SymbolName = "waypoint_210";
            multisymbolitem43.Transparent = false;
            symbolinterval43.Value = multisymbolitem43;
            symbolinterval44.End = 217D;
            symbolinterval44.Start = 213D;
            multisymbolitem44.SymbolName = "waypoint_215";
            multisymbolitem44.Transparent = false;
            symbolinterval44.Value = multisymbolitem44;
            symbolinterval45.End = 222D;
            symbolinterval45.Start = 218D;
            multisymbolitem45.SymbolName = "waypoint_220";
            multisymbolitem45.Transparent = false;
            symbolinterval45.Value = multisymbolitem45;
            symbolinterval46.End = 227D;
            symbolinterval46.Start = 223D;
            multisymbolitem46.SymbolName = "waypoint_225";
            multisymbolitem46.Transparent = false;
            symbolinterval46.Value = multisymbolitem46;
            symbolinterval47.End = 232D;
            symbolinterval47.Start = 228D;
            multisymbolitem47.SymbolName = "waypoint_230";
            multisymbolitem47.Transparent = false;
            symbolinterval47.Value = multisymbolitem47;
            symbolinterval48.End = 237D;
            symbolinterval48.Start = 233D;
            multisymbolitem48.SymbolName = "waypoint_235";
            multisymbolitem48.Transparent = false;
            symbolinterval48.Value = multisymbolitem48;
            symbolinterval49.End = 242D;
            symbolinterval49.Start = 238D;
            multisymbolitem49.SymbolName = "waypoint_240";
            multisymbolitem49.Transparent = false;
            symbolinterval49.Value = multisymbolitem49;
            symbolinterval50.End = 247D;
            symbolinterval50.Start = 243D;
            multisymbolitem50.SymbolName = "waypoint_245";
            multisymbolitem50.Transparent = false;
            symbolinterval50.Value = multisymbolitem50;
            symbolinterval51.End = 252D;
            symbolinterval51.Start = 248D;
            multisymbolitem51.SymbolName = "waypoint_250";
            multisymbolitem51.Transparent = false;
            symbolinterval51.Value = multisymbolitem51;
            symbolinterval52.End = 257D;
            symbolinterval52.Start = 253D;
            multisymbolitem52.SymbolName = "waypoint_255";
            multisymbolitem52.Transparent = false;
            symbolinterval52.Value = multisymbolitem52;
            symbolinterval53.End = 262D;
            symbolinterval53.Start = 258D;
            multisymbolitem53.SymbolName = "waypoint_260";
            multisymbolitem53.Transparent = false;
            symbolinterval53.Value = multisymbolitem53;
            symbolinterval54.End = 267D;
            symbolinterval54.Start = 263D;
            multisymbolitem54.SymbolName = "waypoint_265";
            multisymbolitem54.Transparent = false;
            symbolinterval54.Value = multisymbolitem54;
            symbolinterval55.End = 272D;
            symbolinterval55.Start = 268D;
            multisymbolitem55.SymbolName = "waypoint_270";
            multisymbolitem55.Transparent = false;
            symbolinterval55.Value = multisymbolitem55;
            symbolinterval56.End = 277D;
            symbolinterval56.Start = 273D;
            multisymbolitem56.SymbolName = "waypoint_275";
            multisymbolitem56.Transparent = false;
            symbolinterval56.Value = multisymbolitem56;
            symbolinterval57.End = 282D;
            symbolinterval57.Start = 278D;
            multisymbolitem57.SymbolName = "waypoint_280";
            multisymbolitem57.Transparent = false;
            symbolinterval57.Value = multisymbolitem57;
            symbolinterval58.End = 287D;
            symbolinterval58.Start = 283D;
            multisymbolitem58.SymbolName = "waypoint_285";
            multisymbolitem58.Transparent = false;
            symbolinterval58.Value = multisymbolitem58;
            symbolinterval59.End = 292D;
            symbolinterval59.Start = 288D;
            multisymbolitem59.SymbolName = "waypoint_290";
            multisymbolitem59.Transparent = false;
            symbolinterval59.Value = multisymbolitem59;
            symbolinterval60.End = 297D;
            symbolinterval60.Start = 293D;
            multisymbolitem60.SymbolName = "waypoint_295";
            multisymbolitem60.Transparent = false;
            symbolinterval60.Value = multisymbolitem60;
            symbolinterval61.End = 302D;
            symbolinterval61.Start = 298D;
            multisymbolitem61.SymbolName = "waypoint_300";
            multisymbolitem61.Transparent = false;
            symbolinterval61.Value = multisymbolitem61;
            symbolinterval62.End = 307D;
            symbolinterval62.Start = 303D;
            multisymbolitem62.SymbolName = "waypoint_305";
            multisymbolitem62.Transparent = false;
            symbolinterval62.Value = multisymbolitem62;
            symbolinterval63.End = 312D;
            symbolinterval63.Start = 308D;
            multisymbolitem63.SymbolName = "waypoint_310";
            multisymbolitem63.Transparent = false;
            symbolinterval63.Value = multisymbolitem63;
            symbolinterval64.End = 317D;
            symbolinterval64.Start = 313D;
            multisymbolitem64.SymbolName = "waypoint_315";
            multisymbolitem64.Transparent = false;
            symbolinterval64.Value = multisymbolitem64;
            symbolinterval65.End = 322D;
            symbolinterval65.Start = 318D;
            multisymbolitem65.SymbolName = "waypoint_320";
            multisymbolitem65.Transparent = false;
            symbolinterval65.Value = multisymbolitem65;
            symbolinterval66.End = 327D;
            symbolinterval66.Start = 323D;
            multisymbolitem66.SymbolName = "waypoint_325";
            multisymbolitem66.Transparent = false;
            symbolinterval66.Value = multisymbolitem66;
            symbolinterval67.End = 332D;
            symbolinterval67.Start = 328D;
            multisymbolitem67.SymbolName = "waypoint_330";
            multisymbolitem67.Transparent = false;
            symbolinterval67.Value = multisymbolitem67;
            symbolinterval68.End = 337D;
            symbolinterval68.Start = 333D;
            multisymbolitem68.SymbolName = "waypoint_335";
            multisymbolitem68.Transparent = false;
            symbolinterval68.Value = multisymbolitem68;
            symbolinterval69.End = 342D;
            symbolinterval69.Start = 338D;
            multisymbolitem69.SymbolName = "waypoint_340";
            multisymbolitem69.Transparent = false;
            symbolinterval69.Value = multisymbolitem69;
            symbolinterval70.End = 347D;
            symbolinterval70.Start = 343D;
            multisymbolitem70.SymbolName = "waypoint_345";
            multisymbolitem70.Transparent = false;
            symbolinterval70.Value = multisymbolitem70;
            symbolinterval71.End = 352D;
            symbolinterval71.Start = 348D;
            multisymbolitem71.SymbolName = "waypoint_350";
            multisymbolitem71.Transparent = false;
            symbolinterval71.Value = multisymbolitem71;
            symbolinterval72.End = 357D;
            symbolinterval72.Start = 353D;
            multisymbolitem72.SymbolName = "waypoint_355";
            multisymbolitem72.Transparent = false;
            symbolinterval72.Value = multisymbolitem72;
            symbolinterval73.End = 360D;
            symbolinterval73.Start = 358D;
            multisymbolitem73.SymbolName = "waypoint_0";
            multisymbolitem73.Transparent = false;
            symbolinterval73.Value = multisymbolitem73;
            symbolintervalmapper1.Intervals.Add(symbolinterval1);
            symbolintervalmapper1.Intervals.Add(symbolinterval2);
            symbolintervalmapper1.Intervals.Add(symbolinterval3);
            symbolintervalmapper1.Intervals.Add(symbolinterval4);
            symbolintervalmapper1.Intervals.Add(symbolinterval5);
            symbolintervalmapper1.Intervals.Add(symbolinterval6);
            symbolintervalmapper1.Intervals.Add(symbolinterval7);
            symbolintervalmapper1.Intervals.Add(symbolinterval8);
            symbolintervalmapper1.Intervals.Add(symbolinterval9);
            symbolintervalmapper1.Intervals.Add(symbolinterval10);
            symbolintervalmapper1.Intervals.Add(symbolinterval11);
            symbolintervalmapper1.Intervals.Add(symbolinterval12);
            symbolintervalmapper1.Intervals.Add(symbolinterval13);
            symbolintervalmapper1.Intervals.Add(symbolinterval14);
            symbolintervalmapper1.Intervals.Add(symbolinterval15);
            symbolintervalmapper1.Intervals.Add(symbolinterval16);
            symbolintervalmapper1.Intervals.Add(symbolinterval17);
            symbolintervalmapper1.Intervals.Add(symbolinterval18);
            symbolintervalmapper1.Intervals.Add(symbolinterval19);
            symbolintervalmapper1.Intervals.Add(symbolinterval20);
            symbolintervalmapper1.Intervals.Add(symbolinterval21);
            symbolintervalmapper1.Intervals.Add(symbolinterval22);
            symbolintervalmapper1.Intervals.Add(symbolinterval23);
            symbolintervalmapper1.Intervals.Add(symbolinterval24);
            symbolintervalmapper1.Intervals.Add(symbolinterval25);
            symbolintervalmapper1.Intervals.Add(symbolinterval26);
            symbolintervalmapper1.Intervals.Add(symbolinterval27);
            symbolintervalmapper1.Intervals.Add(symbolinterval28);
            symbolintervalmapper1.Intervals.Add(symbolinterval29);
            symbolintervalmapper1.Intervals.Add(symbolinterval30);
            symbolintervalmapper1.Intervals.Add(symbolinterval31);
            symbolintervalmapper1.Intervals.Add(symbolinterval32);
            symbolintervalmapper1.Intervals.Add(symbolinterval33);
            symbolintervalmapper1.Intervals.Add(symbolinterval34);
            symbolintervalmapper1.Intervals.Add(symbolinterval35);
            symbolintervalmapper1.Intervals.Add(symbolinterval36);
            symbolintervalmapper1.Intervals.Add(symbolinterval37);
            symbolintervalmapper1.Intervals.Add(symbolinterval38);
            symbolintervalmapper1.Intervals.Add(symbolinterval39);
            symbolintervalmapper1.Intervals.Add(symbolinterval40);
            symbolintervalmapper1.Intervals.Add(symbolinterval41);
            symbolintervalmapper1.Intervals.Add(symbolinterval42);
            symbolintervalmapper1.Intervals.Add(symbolinterval43);
            symbolintervalmapper1.Intervals.Add(symbolinterval44);
            symbolintervalmapper1.Intervals.Add(symbolinterval45);
            symbolintervalmapper1.Intervals.Add(symbolinterval46);
            symbolintervalmapper1.Intervals.Add(symbolinterval47);
            symbolintervalmapper1.Intervals.Add(symbolinterval48);
            symbolintervalmapper1.Intervals.Add(symbolinterval49);
            symbolintervalmapper1.Intervals.Add(symbolinterval50);
            symbolintervalmapper1.Intervals.Add(symbolinterval51);
            symbolintervalmapper1.Intervals.Add(symbolinterval52);
            symbolintervalmapper1.Intervals.Add(symbolinterval53);
            symbolintervalmapper1.Intervals.Add(symbolinterval54);
            symbolintervalmapper1.Intervals.Add(symbolinterval55);
            symbolintervalmapper1.Intervals.Add(symbolinterval56);
            symbolintervalmapper1.Intervals.Add(symbolinterval57);
            symbolintervalmapper1.Intervals.Add(symbolinterval58);
            symbolintervalmapper1.Intervals.Add(symbolinterval59);
            symbolintervalmapper1.Intervals.Add(symbolinterval60);
            symbolintervalmapper1.Intervals.Add(symbolinterval61);
            symbolintervalmapper1.Intervals.Add(symbolinterval62);
            symbolintervalmapper1.Intervals.Add(symbolinterval63);
            symbolintervalmapper1.Intervals.Add(symbolinterval64);
            symbolintervalmapper1.Intervals.Add(symbolinterval65);
            symbolintervalmapper1.Intervals.Add(symbolinterval66);
            symbolintervalmapper1.Intervals.Add(symbolinterval67);
            symbolintervalmapper1.Intervals.Add(symbolinterval68);
            symbolintervalmapper1.Intervals.Add(symbolinterval69);
            symbolintervalmapper1.Intervals.Add(symbolinterval70);
            symbolintervalmapper1.Intervals.Add(symbolinterval71);
            symbolintervalmapper1.Intervals.Add(symbolinterval72);
            symbolintervalmapper1.Intervals.Add(symbolinterval73);
            this.m_MultiPicture.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_MultiPicture.SymbolName = "waypoint_0";
            this.m_MultiPicture.Top = 192;
            this.m_MultiPicture.Value = 0D;
            this.m_MultiPicture.VisibleDynamicsValue = true;
            this.m_MultiPicture.Width = 100;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.DelayMouseInputPeriod = 0;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontSizePixels = 20;
            this.m_Text1.Height = 25;
            this.m_Text1.Left = 488;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 0D, 5D, 1D);
            this.m_Text1.ScreenOwnerName = "Assisted_Insert";
            this.m_Text1.Top = 152;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 110;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "Assisted_Insert";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_Assisted_Insert = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_Assisted_Insert) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric);
            this.DrawingPrimitives.Add(this.m_MultiPicture);
            this.DrawingPrimitives.Add(this.m_Text1);
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_MultiPicture)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Assisted_Insert));
            this.m_Text.Text = resources.GetText("Assisted_Insert.Text.Text", "ASSISTED INSERT");
            this.m_Text2.Text = resources.GetText("Assisted_Insert.Text2.Text", "Distance to Point (mm)");
            this.m_Text1.Text = resources.GetText("Assisted_Insert.Text1.Text", "Heading to Point ");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_Assisted_Insert) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.AI_Distance"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.AI_Heading"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_MultiPicture.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
        }
    }
}
